package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Test'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Test")) {
    expectTemplates()
    templates = arrayListOf(RelativeId("TestTemaplte"))

    vcs {

        check(checkoutMode == CheckoutMode.ON_AGENT) {
            "Unexpected option value: checkoutMode = $checkoutMode"
        }
        checkoutMode = CheckoutMode.AUTO

        check(cleanCheckout == true) {
            "Unexpected option value: cleanCheckout = $cleanCheckout"
        }
        cleanCheckout = false

        remove(AbsoluteId("MamkinDevopsVcsRoot"))
    }

    expectSteps {
        script {
            name = "frontend/unit"
            scriptContent = """
                #!/bin/bash
                
                export NVM_DIR="${'$'}HOME/.nvm"
                [ -s "${'$'}NVM_DIR/nvm.sh" ] && \. "${'$'}NVM_DIR/nvm.sh"  # This loads nvm
                
                echo "testing"
                make -C ./frontend test/unit
            """.trimIndent()
        }
    }
    steps {
        items.removeAt(0)
    }

    triggers {
        remove {
            vcs {
                id = "TRIGGER_1"
            }
        }
    }
}
